import {
  Box,
  Button,
  Chip,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from "@mui/material";

import DownloadIcon from "@mui/icons-material/Download";

import CardContainer from "../Common/CardContainer";

// ======================================
// Mock Data
// Replace with backend data later
// ======================================

const reports = [
  {
    id: 1,
    name: "Monthly User Report",
    type: "PDF",
    generatedBy: "Admin",
    generatedDate: "08 Jul 2026",
  },
  {
    id: 2,
    name: "Skill Library Report",
    type: "Excel",
    generatedBy: "Admin",
    generatedDate: "07 Jul 2026",
  },
  {
    id: 3,
    name: "Career Goal Report",
    type: "PDF",
    generatedBy: "Admin",
    generatedDate: "05 Jul 2026",
  },
  {
    id: 4,
    name: "CV Upload Report",
    type: "Excel",
    generatedBy: "System",
    generatedDate: "04 Jul 2026",
  },
];

const RecentReportsTable = () => {
  return (
    <CardContainer>

      <Typography
        variant="h6"
        sx={{
          fontWeight: "bold",
          color: "#0F172A",
          mb: 3,
        }}
      >
        Recent Generated Reports
      </Typography>

      <TableContainer>

        <Table>

          <TableHead>

            <TableRow>

              <TableCell>
                <strong>Report Name</strong>
              </TableCell>

              <TableCell>
                <strong>Type</strong>
              </TableCell>

              <TableCell>
                <strong>Generated By</strong>
              </TableCell>

              <TableCell>
                <strong>Date</strong>
              </TableCell>

              <TableCell align="center">
                <strong>Download</strong>
              </TableCell>

            </TableRow>

          </TableHead>

          <TableBody>

            {reports.map((report) => (

              <TableRow
                hover
                key={report.id}
              >

                <TableCell>

                  <Typography sx={{
                
                   fontWeight:600
                }}
                   >
                    {report.name}
                  </Typography>

                </TableCell>

                <TableCell>

                  <Chip
                    label={report.type}
                    color={
                      report.type === "PDF"
                        ? "error"
                        : "success"
                    }
                    size="small"
                  />

                </TableCell>

                <TableCell>

                  {report.generatedBy}

                </TableCell>

                <TableCell>

                  {report.generatedDate}

                </TableCell>

                <TableCell align="center">

                  <Button
                    variant="outlined"
                    size="small"
                    startIcon={<DownloadIcon />}
                    sx={{
                      textTransform: "none",
                    }}
                  >
                    Download
                  </Button>

                </TableCell>

              </TableRow>

            ))}

          </TableBody>

        </Table>

      </TableContainer>

    </CardContainer>
  );
};

export default RecentReportsTable;