services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./jobs_dataset_skills_final.csv:/seed/jobs_dataset_skills_final.csv
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongo-data:
